<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitGPAI
{
    public static $prefixLengthsPsr4 = array (
        'f' => 
        array (
            'franciscoblancojn\\wordpress_utils\\' => 34,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'franciscoblancojn\\wordpress_utils\\' => 
        array (
            0 => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'franciscoblancojn\\wordpress_utils\\FWUSystemLog' => __DIR__ . '/..' . '/franciscoblancojn/wordpress_utils/src/FWUSystemLog.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitGPAI::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitGPAI::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitGPAI::$classMap;

        }, null, ClassLoader::class);
    }
}
